### ISSUE TITLE
Some ideas for improvements on README and Sample App

### ISSUE THREAD

**Issue by worker8** [cookpad/OkReport#4]
First of all.. thanks for this awesome library, looking forward to a better future for managing bugs 🐛 💪 

I can think of a few suggestions:

**for Readme**
- R1. shorten gifs into url. If we hide the gifs at first will be better IMO so that reader can focus of one at a time rather than many gifs flashing around. We can perhaps keep the main one as the demo though.
- R2. removing `gifs` file from this repo, drag and drop into an issue, and copy the link, this way the repo size can be reduced. We might need to do some force pushing though... 🤔 ?
- R3. [nits] Slack screenshot can include a little more Slack UI to make it look more like Slack, also including the icon will be good.
- R4. Workflow related gifs can be turned into series of screenshot with annotation. I think it can make it easier to understand.
- R5. Explain about no-op version, why it is needed (because we don't want this to show in production blabla..)
- R6. Add more Credits, such as:
  - com.squareup:seismic
  - com.github.nisrulz:screenshott

**for Sample App**
- S1. add an APK to the PlayStore
- S2. the example is rotating the screenshots once initiated ー I have issues with understanding what it is doing, I stupidly clicked on those buttons for a good 10+ seconds before realizing they are images 😂😳 ... 
   - how about changing the main page to show a paragraph explaining what this library is doing, and say "Shake Your Phone!", once the user shake the app, they will see this library in action.
   - the rotating screenshots example is actually good for showing the steps feature, we can keep this example but I think hiding it inside a SideMenu will be better.
   - another idea of showing the step feature will be to make state changes to a screen (let's say a counter keep counting up/ changing gradient of background), and ask the user to shake the phone again, the 2nd time they shake the phone, they will see that they capture a different screen.
- S3. add link to Github, like an icon at the top bar or something..
- S4. compiling the app throws error at first because we need to setup the Slack integration.
   - how about default it to `""`, app will compile, but clicking `send` later will throw error, during the error, we can say "looks like you haven't setup Slack integration... go to this Link to learn how to setup". Now they know what this library is doing, they will be interested enough to find out.
- S5. add example to showcase how to customize `Gesture` and `Reporter`

I added numbering so that it's easier to reference for discussion 😆

**Comment by VictorAlbertos** [comment]
Thanks for the suggestions @worker8 :)

- [x] **R1** and **R2** are implicitly solved by addressing **R4**, which I think it's a better idea rather than having gifs (actually, by having screenshot instead of gifs I'd be more motivated to keep them update it -because it's easier) - I'll do it.

- [x] **R5**, **R6** and **S5** I'll do it.

* **R3** I did my best 😅. Would you open a PR to improve it please?

* **S1**, **S2** and **S3** I think they would be a nice thing to have in the long run, but right now I'm not too motivated to do that given the early stage of the lib. But, of course, if you're willing to do it, please do it :) 

* **S4** I don't understand how do you want to default to `""` without changing the library itself. Would you create a PR to illustrate please?

**Comment by worker8** [comment]
Before you do S5, you might want to take a look at this first 👇 
https://github.com/cookpad/OkReport/pull/5

because it might affect the example.

**Comment by worker8** [comment]
Agree that S1 is not ready yet. I can do it, but it's going to be under my account though... Let's discuss about this when it's ready XD

For R3, S2, and S3, I can make some PRs when I have time~

As for S4, I mean something like this --> https://github.com/cookpad/OkReport/pull/6
